---

networks:
  deluge-net:
    ipam:
      driver: bridge
      config:
        - subnet: 172.20.0.0/16

services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    hostname: deluge
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /mnt/5dd038e4-e1e4-46fb-8c77-cd3dfc661647/deluge/config:/config
      - /mnt/5dd038e4-e1e4-46fb-8c77-cd3dfc661647/media:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
    networks:
      deluge-net:
        ipv4_address: 172.20.0.2
